### PR TITLE
Added GuessingGame and ImageConverter

### PR DESCRIPTION
**Pull request by yashppawar**
Hi, these programmes are of my best, it would really help me build my confidence if you accept my pull request, Thank You very much!!!!!!!!!

### CODE REVIEW

**Comment by jYOTIHARODE** [comment]
Thank you for your contribution!

**Comment by jYOTIHARODE** [comment]
Thank you @yashppawar  for your contribution!
keep going!

**Comment by yashppawar** [comment]
Thank You very much, Ma'am!

**Comment by jYOTIHARODE** [comment]
Welcome 😊

**Pull request merged**
